// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIknLCFv_QUkHKcsHC1TCmxhGMOxANtJo',
    appId: '1:1048554784842:web:a28cd476bc15f181bf3eb3',
    messagingSenderId: '1048554784842',
    projectId: 'logn-notes',
    authDomain: 'logn-notes.firebaseapp.com',
    storageBucket: 'logn-notes.firebasestorage.app',
    measurementId: 'G-D1LNPEC5FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHoAP8Idg4HRR0WUxP_N81gFLB77XY3QM',
    appId: '1:1048554784842:android:fa5da0b5174129b0bf3eb3',
    messagingSenderId: '1048554784842',
    projectId: 'logn-notes',
    storageBucket: 'logn-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhEG5WjQ0gbqaxt54P0nir_UTPwCgTaNQ',
    appId: '1:1048554784842:ios:4c73e28e370212d5bf3eb3',
    messagingSenderId: '1048554784842',
    projectId: 'logn-notes',
    storageBucket: 'logn-notes.firebasestorage.app',
    iosBundleId: 'com.logncomplexity.notes',
  );
}
